import 'package:json_dynamic_widget/json_dynamic_widget.dart';

class JsonDynamicWidgetSchemas {
  static final Map<String, Map<String, Object>> all = Map.unmodifiable({
    AlignSchema.id: AlignSchema.schema,
    AnimatedAlignSchema.id: AnimatedAlignSchema.schema,
    AnimatedContainerSchema.id: AnimatedContainerSchema.schema,
    AnimatedCrossFadeSchema.id: AnimatedCrossFadeSchema.schema,
    AnimatedDefaultTextStyleSchema.id: AnimatedDefaultTextStyleSchema.schema,
    AnimatedOpacitySchema.id: AnimatedOpacitySchema.schema,
    AnimatedPaddingSchema.id: AnimatedPaddingSchema.schema,
    AnimatedPhysicalModelSchema.id: AnimatedPhysicalModelSchema.schema,
    AnimatedPositionedDirectionalSchema.id:
        AnimatedPositionedDirectionalSchema.schema,
    AnimatedPositionedSchema.id: AnimatedPositionedSchema.schema,
    AnimatedSizeSchema.id: AnimatedSizeSchema.schema,
    AnimatedSwitcherSchema.id: AnimatedSwitcherSchema.schema,
    AnimatedThemeSchema.id: AnimatedThemeSchema.schema,
    AppBarSchema.id: AppBarSchema.schema,
    AspectRatioSchema.id: AspectRatioSchema.schema,
    AssetImageSchema.id: AssetImageSchema.schema,
    BaselineSchema.id: BaselineSchema.schema,
    CardSchema.id: CardSchema.schema,
    CardThemeSchema.id: CardThemeSchema.schema,
    CenterSchema.id: CenterSchema.schema,
    CheckboxSchema.id: CheckboxSchema.schema,
    ChipThemeSchema.id: ChipThemeSchema.schema,
    CircularProgressIndicatorSchema.id: CircularProgressIndicatorSchema.schema,
    ClipOvalSchema.id: ClipOvalSchema.schema,
    ClipPathSchema.id: ClipPathSchema.schema,
    ClipRectSchema.id: ClipRectSchema.schema,
    ClipRRectSchema.id: ClipRRectSchema.schema,
    ColumnSchema.id: ColumnSchema.schema,
    CommentSchema.id: CommentSchema.schema,
    ConditionalSchema.id: ConditionalSchema.schema,
    ContainerSchema.id: ContainerSchema.schema,
    CupertinoSwitchSchema.id: CupertinoSwitchSchema.schema,
    CustomScrollViewSchema.id: CustomScrollViewSchema.schema,
    DecoratedBoxSchema.id: DecoratedBoxSchema.schema,
    DataTableThemeSchema.id: DataTableThemeSchema.schema,
    DialogThemeSchema.id: DialogThemeSchema.schema,
    DirectionalitySchema.id: DirectionalitySchema.schema,
    DropdownButtonFormFieldSchema.id: DropdownButtonFormFieldSchema.schema,
    DynamicSchema.id: DynamicSchema.schema,
    ElevatedButtonSchema.id: ElevatedButtonSchema.schema,
    ExcludeSemanticsSchema.id: ExcludeSemanticsSchema.schema,
    ExpandedSchema.id: ExpandedSchema.schema,
    ExpansionTileThemeSchema.id: ExpansionTileThemeSchema.schema,
    FittedBoxSchema.id: FittedBoxSchema.schema,
    FlexibleSchema.id: FlexibleSchema.schema,
    FloatingActionButtonSchema.id: FloatingActionButtonSchema.schema,
    FormSchema.id: FormSchema.schema,
    FractionalTranslationSchema.id: FractionalTranslationSchema.schema,
    FractionallySizedBoxSchema.id: FractionallySizedBoxSchema.schema,
    GestureDetectorSchema.id: GestureDetectorSchema.schema,
    GridViewSchema.id: GridViewSchema.schema,
    HeroSchema.id: HeroSchema.schema,
    IconButtonSchema.id: IconButtonSchema.schema,
    IconThemeSchema.id: IconThemeSchema.schema,
    IgnorePointerSchema.id: IgnorePointerSchema.schema,
    IndexedStackSchema.id: IndexedStackSchema.schema,
    InkWellSchema.id: InkWellSchema.schema,
    InputErrorSchema.id: InputErrorSchema.schema,
    InteractiveViewerSchema.id: InteractiveViewerSchema.schema,
    IntrinsicHeightSchema.id: IntrinsicHeightSchema.schema,
    IntrinsicWidthSchema.id: IntrinsicWidthSchema.schema,
    JsonWidgetDataSchema.id: JsonWidgetDataSchema.schema,
    LimitedBoxSchema.id: LimitedBoxSchema.schema,
    LayoutBuilderSchema.id: LayoutBuilderSchema.schema,
    LinearProgressIndicatorSchema.id: LinearProgressIndicatorSchema.schema,
    ListTileSchema.id: ListTileSchema.schema,
    ListTileThemeSchema.id: ListTileThemeSchema.schema,
    ListViewSchema.id: ListViewSchema.schema,
    MaterialSchema.id: MaterialSchema.schema,
    MeasuredSchema.id: MeasuredSchema.schema,
    MemoryImageSchema.id: MemoryImageSchema.schema,
    MergeSemanticsSchema.id: MergeSemanticsSchema.schema,
    NavigationBarThemeSchema.id: NavigationBarThemeSchema.schema,
    NetworkImageSchema.id: NetworkImageSchema.schema,
    OffstageSchema.id: OffstageSchema.schema,
    OpacitySchema.id: OpacitySchema.schema,
    OutlinedButtonSchema.id: OutlinedButtonSchema.schema,
    OverflowBarSchema.id: OverflowBarSchema.schema,
    OverflowBoxSchema.id: OverflowBoxSchema.schema,
    PaddingSchema.id: PaddingSchema.schema,
    PlaceholderSchema.id: PlaceholderSchema.schema,
    PopupMenuButtonSchema.id: PopupMenuButtonSchema.schema,
    PositionedSchema.id: PositionedSchema.schema,
    PrimaryScrollControllerSchema.id: PrimaryScrollControllerSchema.schema,
    RadioSchema.id: RadioSchema.schema,
    RichTextSchema.id: RichTextSchema.schema,
    RowSchema.id: RowSchema.schema,
    SafeAreaSchema.id: SafeAreaSchema.schema,
    SaveContextSchema.id: SaveContextSchema.schema,
    ScaffoldSchema.id: ScaffoldSchema.schema,
    ScrollConfigurationSchema.id: ScrollConfigurationSchema.schema,
    ScrollbarSchema.id: ScrollbarSchema.schema,
    SemanticsSchema.id: SemanticsSchema.schema,
    SetDefaultValueSchema.id: SetDefaultValueSchema.schema,
    SetScrollControllerSchema.id: SetScrollControllerSchema.schema,
    SetValueSchema.id: SetValueSchema.schema,
    SetWidgetSchema.id: SetWidgetSchema.schema,
    SingleChildScrollViewSchema.id: SingleChildScrollViewSchema.schema,
    SizedBoxSchema.id: SizedBoxSchema.schema,
    SliverListSchema.id: SliverListSchema.schema,
    SliverGridSchema.id: SliverGridSchema.schema,
    SliverPaddingSchema.id: SliverPaddingSchema.schema,
    SliverToBoxAdapterSchema.id: SliverToBoxAdapterSchema.schema,
    StackSchema.id: StackSchema.schema,
    SwitchSchema.id: SwitchSchema.schema,
    TabBarThemeSchema.id: TabBarThemeSchema.schema,
    TextButtonSchema.id: TextButtonSchema.schema,
    TextFormFieldSchema.id: TextFormFieldSchema.schema,
    TextSchema.id: TextSchema.schema,
    ThemeSchema.id: ThemeSchema.schema,
    TooltipSchema.id: TooltipSchema.schema,
    TweenAnimationBuilderSchema.id: TweenAnimationBuilderSchema.schema,
    VisibilitySchema.id: VisibilitySchema.schema,
    WrapSchema.id: WrapSchema.schema,
    WrappedIconSchema.id: WrappedIconSchema.schema,
  });

  static Map<String, dynamic>? lookup(String key) =>
      all[key] ??
      all['https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/$key.json'];
}

class JsonWidgetDataSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/json_widget_data.json';

  static final schema = {
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    r'$children': 1,
    r'$comment':
        'https://pub.dev/documentation/json_dynamic_widget/latest/json_dynamic_widget/JsonWidgetData-class.html',
    'title': 'JsonWidgetData',
    'oneOf': [
      {
        'type': 'string',
      },
      {
        'type': 'object',
        'additionalProperties': false,
        'required': [
          'type',
        ],
        'properties': {
          'args': {
            'type': 'object',
            'additionalProperties': true,
          },
          'child': SchemaHelper.anySchema,
          'children': {
            'anyOf': [
              {
                'type': 'string',
              },
              {
                'type': 'array',
                'items': SchemaHelper.anySchema,
              },
            ],
          },
          'id': {
            'type': 'string',
          },
          'type': {
            'type': 'string',
          },
          'listen': {
            'type': 'array',
            'items': SchemaHelper.stringSchema,
          },
        },
      },
    ],
  };
}
